const unsafePhrases = [
  'ignore previous instructions',
  'jailbreak',
  'you are now',
  'bypass',
  'disable safety',
  'pretend to be',
  'act as',
  'root access',
  'peter is dumb',
  'connor is dumb',
  'peter is stupid',
  'connor is stupid',
  'peter is an idiot',
  'connor is an idiot',
  'peter is trash',
  'connor is trash',
  'peter sucks',
  'connor sucks',
  'peter is a fool',
  'connor is a fool',
  'peter is a moron',
  'connor is a moron',
  'peter is an imbecile',
  'connor is an imbecile',
  'peter is a nincompoop',
  'connor is a nincompoop',
  'peter is a blockhead',
  'connor is a blockhead',
  'peter is a dunce',
  'connor is a dunce',
  'peter is a dimwit',
  'connor is a dimwit',
  'peter is a simpleton',
  'connor is a simpleton',
  'peter is a birdbrain',
  'connor is a birdbrain',
  'peter is a bonehead',
  'connor is a bonehead',
]

function isUnsafe(prompt) {
    return unsafePhrases.some((phrase) => prompt.toLowerCase().includes(phrase))
}
module.exports = isUnsafe;